### PR TITLE
User racha history

### PR DESCRIPTION
**Pull request by edukatiau**
The user will be able to see his/her racha history as a participant

### CODE REVIEW

**Comment by dr03ramos** [comment]
@edukatiau wouldn't it be a good idea to also list all the rachas that a user owns on this branch as well?

**Comment by edukatiau** [comment]
> @edukatiau wouldn't it be a good idea to also list all the rachas that a user owns on this branch as well?

@dr03ramos Since we already have an endpoint that only returns an owner's racha, all that's missing is a list of the racha the user participates in. We can talk to the rest of the team to decide how to proceed.

**Review by dr03ramos — DISMISSED** [review]

**Review by dr03ramos — CHANGES_REQUESTED** [review]
Made some changes to remove warnings on some linters and formatting.

**Comment by dr03ramos** [comment]
> > Made some changes to remove warnings on some linters and add formatting.
> 
> @dr03ramos Sorry, could you please point out exactly where these changes need to be made? I get no errors or warnings, and everything is formatted.

My apologies. I should've committed my changes.

**Review by dr03ramos — DISMISSED** [review]

**Review by DiegoDexheimer — APPROVED** [review]
Ta good dog

**Review by dr03ramos — APPROVED** [review]

**Pull request merged**
